version: "3.7"
services:
  database:
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=expense_tracker
      - MONGO_INITDB_USERNAME=username
      - MONGO_INITDB_PASSWORD=password
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db

